### ISSUE TITLE
even with all images attached, gatsby still thinks *some* images live on shannon's old server

### ISSUE THREAD

**Issue by samtous** [Kallirroi/wordsinspace#108]
so: the images that were causing issues before are *still* not getting located properly in the new version. These images are attached to the correct posts (and appear in them correctly on her wordpress).

![Screen Shot 2020-08-25 at 13 54 55](https://user-images.githubusercontent.com/5625731/91210020-9b3dd080-e6da-11ea-9933-09fd7ace2f56.png)
![Screen Shot 2020-08-25 at 13 55 04](https://user-images.githubusercontent.com/5625731/91210022-9bd66700-e6da-11ea-9871-f88522db729c.png)

These are going to cause issues when we point wordsinspace at the _new_ url, cause they will no longer be at the old location.

As a final attempt, I am trying a new import where the slideshow images get attachment_urls rather than guids from the wordpress file to see if that fixes it. If that doesn't work, then the next step will be to try updating the problem urls in the database, and if _that_ doesn't work then we might have to just fix manually :(

**Comment by samtous** [comment]
![Screen Shot 2020-08-25 at 16 43 00](https://user-images.githubusercontent.com/5625731/91225780-25456380-e6f2-11ea-8c36-a713d50311a4.png)
This is now _fixed_ for slideshow images but some older images in the body are still not linked properly

**Comment by samtous** [comment]
ok turns out there are a _bunch_ of older images in a weird folder on shannon's site which never got properly attached in the first place :( these are mostly body images for pages pre-2017. I'm going to copy these onto the new server and then see if i can rewrite the links to them in the database so at least they won't be broken!

**Comment by rokeby** [comment]
https://soup.wordsinspace.net/local-codes-forms-of-spatial-knowledge/
https://soup.wordsinspace.net/the-librarys-other-intelligences-mobius-fellowship-with-the-finnish-cultural-institute-ny-2017-19/
https://soup.wordsinspace.net/encrypted-repositories/
https://soup.wordsinspace.net/code-craft-catalogues-arts-in-the-libraries-2019/
https://soup.wordsinspace.net/mapwashing-co-opting-civic-design-2019/
https://soup.wordsinspace.net/interfaces-arent-just-screens-2019/
https://soup.wordsinspace.net/data-fantasies-and-operational-facts-5gs-infrastructural-epistemologies/
https://soup.wordsinspace.net/sidewalks-sidewalk-a-pedestrian-view-of-sidewalk-toronto-2019/
https://soup.wordsinspace.net/encrypted-repositories-2018/
https://soup.wordsinspace.net/machines-ecologies-operating-systems-parasites-city-as-metaphor-2018/
https://soup.wordsinspace.net/local-codes-forms-of-spatial-knowledge-2018/
https://soup.wordsinspace.net/sounding-the-commons-2018/
https://soup.wordsinspace.net/amending-care-an-archaeology-of-maintenance-2018/
https://soup.wordsinspace.net/fifty-thousand-eyes-on-a-scene-2018/
https://soup.wordsinspace.net/the-pulse-of-global-passage-listening-to-logistics-2018/
https://soup.wordsinspace.net/cabinets-codes-catalogues-on-hardware-stores-2018/
https://soup.wordsinspace.net/mapping-as-method-and-medium-2018/
https://soup.wordsinspace.net/teaching/maps-as-media/
https://soup.wordsinspace.net/sounding-the-commons-2018/
https://soup.wordsinspace.net/amending-care-an-archaeology-of-maintenance-2018/
 
Some pages with one or more images broken likely due to them being -scaled by images.php

**Comment by samtous** [comment]
there were another bunch of images that weren't getting linked properly because of a scaling issue. Between [a plugin install](https://wordpress.org/plugins/disable-big-image-threshold/) (which in future should be installed _before_ import), and [this php script](https://stackoverflow.com/questions/59515056/how-to-stop-wordpress-scaling-down-big-images-scaled-jpg/59515057#59515057) it seems to have worked

**Comment by samtous** [comment]
STEPS TO RESIZE TOO LARGE IMAGES (resolves more recent image issue)

//1. finds and makes a copy of every non-pdf file >2MB, moves to __orig
`find . -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" \) -size +1M -printf '%p\n' -exec cp {} {}__orig \;`


//2. finds every non-pdf file > 2M and not an original and converts 
`find . -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" \) ! -name "*__orig" -size +1M -printf '%p\n' -exec convert {} -resize 1500 -quality 99 {} \;`

**Comment by samtous** [comment]
ok wrote a php script to reattach _all_ archival images and tested it on the digital ocean server. Definitely makes the site a lot bigger (and takes ~2h to run) but also it works! will try this later on shannon's server.

**Comment by samtous** [comment]
STEPS TO SUCCESS:
(i have done these; here for posterity)

- [ ] remove all the -scaled images from the db using php script 1
- [ ] resize all the images down so they’re able to be cached using the shell script
- [ ] run the php script that links the archival images (takes like 2h)
- [ ] run the mysql query that removes the ~9 dodgy timestamps
- [ ] trigger local build w new url and test
